# Generated by Django 4.2.1 on 2026-02-17 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyberAuraAdmin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cybeAuraAdmin',
            new_name='cyberAuraAdmin',
        ),
    ]
