# Generated by Django 4.2.1 on 2026-02-18 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberAuraAdmin', '0002_rename_cybeauraadmin_cyberauraadmin'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cyberauraadmin',
            options={'ordering': ['-time_create']},
        ),
        migrations.AddField(
            model_name='cyberauraadmin',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='cyberauraadmin',
            index=models.Index(fields=['-time_create'], name='cyberAuraAd_time_cr_9a726e_idx'),
        ),
    ]
