# Generated by Django 4.2.1 on 2026-02-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberAuraAdmin', '0003_alter_cyberauraadmin_options_cyberauraadmin_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberauraadmin',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
