# Generated by Django 4.2.1 on 2026-02-18 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyberAuraAdmin', '0004_alter_cyberauraadmin_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberauraadmin',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Черновик'), (1, 'Опубликовано')], default=0),
        ),
    ]
