# Generated by Django 4.2.1 on 2026-02-18 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyberAuraAdmin', '0006_category_cyberauraadmin_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cyberauraadmin',
            name='cat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cyberAuraAdmin.category'),
        ),
    ]
